application: windmilltownhomes
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /css
  static_dir: css/
  expiration: '365d'
  
- url: /images
  static_dir: images/
  expiration: '365d'

- url: /js
  static_dir: js/
  expiration: '365d'

- url: /.*
  script: djangoappengine/main/main.py
